languageCode: "en-us"
baseUrl: ""
title: "The Zone"
theme: "anubis"
paginate: 10
# disqusShortname: yourdiscussshortname
# googleAnalytics: UA-123-45
enableRobotsTXT: true

menu:
  main:
#  - identifier: about
#    name: About
#    title: About
#    url: /about/
#    weight: 2
  - identifier: links
    name: Links
    title: Links
    url: /links/
    weight: 1
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0

params:
  author: "Knut"
  description: "A Homepage|Website|Blog?"
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "static" directory
  customJS:
    - js/main.js # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: false
  style: dark-without-switcher
  readMore: true

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
